name: Create Tag and Release

on:
  pull_request:
    branches:
      - master
    types:
      - closed

jobs:
  create_tag:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true && startsWith(github.event.pull_request.head.ref, 'develop/')
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set Tag Name
        id: set_tag_name
        run: echo "::set-output name=tag_name::$(echo ${{ github.event.pull_request.head.ref }} | sed 's/develop\///')"
      
      - name: Fetch and Checkout Branch
        run: |
          git fetch origin ${{ github.event.pull_request.head.ref }}
          git checkout ${{ github.event.pull_request.head.ref }}
      - name: Create Git Tag
        run: |
          git tag "${{ steps.set_tag_name.outputs.tag_name }}"
      - name: Push Git Tag
        run: |
          git push origin "${{ steps.set_tag_name.outputs.tag_name }}"

  release:
    runs-on: ubuntu-latest
    needs: create_tag
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set Tag Name
        id: set_tag_name
        run: echo "::set-output name=tag_name::$(echo ${{ github.event.pull_request.head.ref }} | sed 's/develop\///')"
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.set_tag_name.outputs.tag_name }}
          release_name: ${{ steps.set_tag_name.outputs.tag_name }}
          body: ${{ github.event.pull_request.body }}
          draft: false
          prerelease: false
